apiVersion: v1
kind: Service
metadata:
  name: maquette-protools
spec:
  #type of the service
  type: NodePort
  selector:
    app: maquette-protools
  ports:
    - port: 3050
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
